Milestone 4 Calculator project
imhilla/calculator pull request #6
Opened 2020-10-15 08:33 UTC by imhilla

Hello TSE,
Please review this forth milestone for the React calculator project.
I added the logic to handle calculations and operations. Any feedback will be highly appreciated.

Thanks
Hillary

2020-10-15 11:40 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there @imhilla :hand: 
Awesome job on this milestone so far :clap: 
But we need to make some changes before moving on

- [ ] Check my comments bellow

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-10-15 11:40 UTC, Torres-ssf commented on src/logic/calculate.js
> +    }
- [ ] We need to evaluate more cases here. What should happen if the user press `AC`, `.` or `+/-`? We also need to address these cases.

2020-10-15 11:40 UTC, Torres-ssf commented on src/logic/operate.js
> +    }
- [ ] Make sure to test if the modifier operation works when only number one was typed.

2020-10-17 12:15 UTC, wathigo requested changes
### Changes Required :heavy_multiplication_x: 
Great job on this project :clap: 
Let's make a few changes before we proceed to the next milestone.

**REQUIRED**
* The button name "+/-" should multiply total and next by -1 to make it negative or positive. Currently, an error is thrown upon an attempt to use this functionality.
* Let's add some information on how to get the app running locally to our README file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**After making the changes, submit another request for review.**

**Happy Hacking :computer: 
Simon Wathigo.**

2020-10-17 21:30 UTC, mosaaleb approved these changes
### Well done @imhilla :clap:

Looks like you have handled all requirements from the previous reviews.
You can merge :+1:

##### Muhammad Ebeid

2020-10-18 04:30 UTC, merged